spring:
  datasource:
    url: "${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:petstore}?sslmode=${DB_SSL_MODE:require}}"
    username: ${SPRING_DATASOURCE_USERNAME:petstore}
    password: ${SPRING_DATASOURCE_PASSWORD:petstore}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

server:
  port: 8080

petstore:
  api:
    base-path: /api/simeon
